### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by Resonanz** [themefisher/Influencer-hugo#1]
Icons missing on this page: https://themes.gohugo.io//theme/Influencer-hugo/post/

**Comment by Resonanz** [comment]
Sidebar icons missing on this page: https://themes.gohugo.io//theme/Influencer-hugo/post/markdown-syntax/

**Comment by Somrat37** [comment]
@Resonanz 

I didn't find the missing icon, i saw every icon is showing. can you more specific where is the icon missing?

**Comment by Resonanz** [comment]
<img width="655" alt="Annotation 2019-12-29 072841" src="https://user-images.githubusercontent.com/6218191/71553766-f51dc600-2a79-11ea-9632-c00b5bdd9031.png">

**Comment by Resonanz** [comment]
See the missing pics?

**Comment by Somrat37** [comment]
Yes! i see that missing pics, but you were talk about missing icon
