### ISSUE TITLE
Content goes below top bar on scroll

### ISSUE THREAD

**Issue by kytwb** [themefisher/Influencer-hugo#3]
The content mixes up with the top bar:

<img width="1157" alt="Screen Shot 2020-04-15 at 11 08 41 AM" src="https://user-images.githubusercontent.com/412895/80327578-1c1fb500-882c-11ea-871c-45395c197b80.png">

**Comment by Somrat37** [comment]
I have checked the hole theme, but no section is mixed like that, can you tell me which section is this?

And also make a pull. Because I just update the theme.

**Comment by kytwb** [comment]
It seems to work properly now on the latest demo. Apologies if I created confusion, I just remember going through the theme with @yourcontact and noticing this on my side, so I took a screenshot to later open this issue but I didn't take the time to double check the console to see what was wrong.

Thank you for the recent update! 🙏
