### ISSUE TITLE
Changes on _variables.scss not shown

### ISSUE THREAD

**Issue by arojoal** [themefisher/Influencer-hugo#8]
I'm testing exampleSite by running  "hugo server --themesDir ../.. --debug".
When I try to change any SCSS variable nothing changes on the site.

Using "Hugo Static Site Generator v0.73.0-DEV darwin/amd64"

This is show at hugo's standard output anytime I change _variables.scss... What am I doing wrong?

DEBUG 2020/06/22 23:13:16 Rebuild for events ["\"/Users/rojalval/src/EXPERIMENTOS/HUGO/beloca/themes/influencer-hugo/assets/scss/_variables.scss\": WRITE"]
DEBUG 2020/06/22 23:13:16 found menu: "main", in site config
DEBUG 2020/06/22 23:13:16 found menu: "main", in site config
DEBUG 2020/06/22 23:13:16 found menu: "main", in site config
DEBUG 2020/06/22 23:13:16 found menu: "main", in site config
DEBUG 2020/06/22 23:13:16 found menu: "main", in site config
DEBUG 2020/06/22 23:13:16 found menu: "main", in site config
DEBUG 2020/06/22 23:13:16 Render XML for "sitemap" to "/sitemap.xml"
Total in 4 ms

**Comment by developer-evan** [comment]
please use Hugo extended version.
